BookStore.WEB/Models/ShoppingCart.cs
using BookStore.BLL.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.ApplicationInsights.Extensibility.Implementation;

namespace BookStore.WEB.Models
{
    public class ShoppingCart
    {
        private readonly IOrderService orderService;
        public string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public ShoppingCart(IOrderService service)
        {
            orderService = service;
        }
       
        public string GetCardId(HttpContextBase context)
        {
            if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
            {
                context.Session[CartSessionKey] = context.User.Identity.Name;
            }
            else
            {
                var cartId = context.Session[CartSessionKey];
                if (cartId==null)
                {
                    cartId = Guid.NewGuid().ToString();
                    context.Session[CartSessionKey] = cartId;
                }
            }
            return context.Session[CartSessionKey].ToString();
           
        }
        
    }
}

BookStore.WEB/Models/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BookStore.BLL.DTO;
namespace BookStore.WEB.Models
{
    public class ShoppingCartViewModel
    {
        public List<CartItemDTO> CartItems { get; set; }
        public string returnUrl { get; set; }
        public decimal CartTotal { get; set;
        }
    }
}

BookStore.WEB/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BookStore.BLL.DTO;
using System.Web.Mvc;
using AutoMapper;
using BookStore.BLL.Interface;
using System.Threading.Tasks;
using BookStore.WEB.Models;

namespace BookStore.WEB.Controllers
{
    public class ShoppingCartController : Controller
    {
        
        IOrderService orderService;
        private readonly ShoppingCartFactory shoppingCartFactory;
        public ShoppingCartController(IOrderService service,ShoppingCartFactory factory)
        {
            orderService = service;
            shoppingCartFactory = factory;
        }
        public async Task<ActionResult> Index(string returnUrl,Controller controller)
        {

            var cartId = shoppingCartFactory.GetCart(HttpContext);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId.ShoppingCartId),
                returnUrl = returnUrl,
                CartTotal = await orderService.GetTotal(cartId.ShoppingCartId)
            };
            return View(viewModel);
        }

   
        
        public async Task<ActionResult> RemoveFromCart(int id)
        {
            var cartId = shoppingCartFactory.GetCart(this.HttpContext).ShoppingCartId;
            orderService.RemoveFromCart(id, cartId);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId),
                CartTotal = await orderService.GetTotal(cartId)
            };
            return PartialView("ShowCart", viewModel); 
            
        }
        public async Task<ActionResult> EmptyCart()
        {
            var cartId = shoppingCartFactory.GetCart(this.HttpContext).ShoppingCartId;
            var CartItems = await orderService.GetAllCartItems(cartId);
            if(CartItems.Count ==0)
            {
                ModelState.AddModelError("", "Your cart is empty");
            }
            await orderService.EmptyCart(cartId);
            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = await orderService.GetAllCartItems(cartId),
                CartTotal = await orderService.GetTotal(cartId)
            };
            return PartialView("ShowCart",viewModel);
        }
        



    }
}

BookStore.WEB/Views/ShoppingCart/Index.cshtml
@{
    ViewBag.Title = "Корзина покупок";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your Cart</h2>

<div id="updateCart">
    @Html.Partial("ShowCart")
</div>

BookStore.WEB/Views/ShoppingCart/ShowCart.cshtml
@model BookStore.WEB.Models.ShoppingCartViewModel
<table class="table">
    <thead>
        <tr>
            <th>Cout</th>
            <th>Book</th>
            <th>Price</th>
            <th>Summary Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.CartItems)
        {
            <tr>
                <td>@line.Count</td>
                <td>@line.Book.Name</td>
                <td>@line.Book.Price.ToString("# USD")</td>
                <td>@((line.Book.Price * line.Count).ToString("# USD"))</td>
                <td>
                    @Ajax.ActionLink("Delete", "RemoveFromCart", "ShoppingCart",
                   new { id = line.CartItemId, returnUrl = Model.returnUrl },new AjaxOptions { HttpMethod="GET",UpdateTargetId = "updateCart"
                   } ,new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Summary:</td>
            <td>
                @Model.CartTotal.ToString("# Usd")
            </td>
        </tr>
    </tfoot>
</table>