BookStore.WEB/ViewModels/AuthorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BookStore.WEB.ViewModels
{
    public class AuthorViewModel
    {
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessage = "ФИО должно быть заполнено")]
        public string Name { get; set; }
    }
}

BookStore.WEB/Controllers/Admin/AuthorController.cs
using BookStore.BLL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BookStore.BLL.DTO;
using BookStore.WEB.ViewModels;
using System.Threading.Tasks;

namespace BookStore.WEB.Controllers.Admin
{
    public class AuthorController : Controller
    {
        // GET: Author
        private IBookService _bookService;
        private IAuthorService _authorService;
        private IGenreService _categoryService;

        public AuthorController(IBookService bookService, IAuthorService authorService, IGenreService categoryService)
        {
            _categoryService = categoryService;
            _authorService = authorService;
            _bookService = bookService;
        }
        public ActionResult GetAllAuthors()
        {

            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<AuthorDTO, AuthorViewModel>()).CreateMapper();
            var authors =
                mapper.Map<IEnumerable<AuthorDTO>, List<AuthorViewModel>>(_authorService.GetAllAuthors());
            //var authors = _authorService.GetAllAuthors();

            return PartialView("ShowAuthors", authors);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AuthorViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<AuthorViewModel, AuthorDTO>()).CreateMapper();
                var authorDTO = mapper.Map<AuthorViewModel, AuthorDTO>(viewModel);
                _authorService.CreateAuthor(authorDTO);
                return RedirectToAction("Main", "Book");
            }

            return View(viewModel);
        }
        
        public ActionResult Delete(int id)
        {
            _authorService.DeleteAuthor(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<AuthorDTO, AuthorViewModel>()).CreateMapper();
            var authors =
                mapper.Map<IEnumerable<AuthorDTO>, IEnumerable<AuthorViewModel>>(_authorService.GetAllAuthors());
            return PartialView("ShowAuthors", authors);
        }
        public ActionResult Edit(int id)
        {
            var authorDTO = _authorService.GetAuthor(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<AuthorDTO, AuthorViewModel>()).CreateMapper();
            var viewModel = mapper.Map<AuthorDTO, AuthorViewModel>(authorDTO);
            return PartialView(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AuthorViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<AuthorViewModel, AuthorDTO>()).CreateMapper();
                var authorDTO = mapper.Map<AuthorViewModel, AuthorDTO>(viewModel);
                _authorService.Update(authorDTO);
                var mapperAuth = new MapperConfiguration(cfg => cfg.CreateMap<AuthorDTO, AuthorViewModel>()).CreateMapper();
                var authors =
                    mapperAuth.Map<IEnumerable<AuthorDTO>, List<AuthorViewModel>>(_authorService.GetAllAuthors());
                return PartialView("ShowAuthors", authors);
               
            }
            
            return PartialView("Edit", viewModel);

        }
    }
}

BookStore.WEB/Views/Author/Create.cshtml
@model BookStore.WEB.ViewModels.AuthorViewModel
@{
    ViewBag.Title = "Add Author";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Add Author</h4>
@using (Html.BeginForm("Create","Author"))
{
    @Html.AntiForgeryToken()
<div class="form-group">
    <label>Name</label>
    @Html.EditorFor(m => m.Name, null, new { htmlAttributes = new { @class = "form-control col-sm-4" } })
    @Html.ValidationMessageFor(m=>m.Name)
</div>
    <input type="submit" value="Submit" class="btn btn-primary"/>
}

BookStore.WEB/Views/Author/Edit.cshtml
@model  BookStore.WEB.ViewModels.AuthorViewModel
<div>
    @using (Ajax.BeginForm("Edit", "Author", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "updateAdminPanel", OnSuccess = "closeDialog()" }))
    { 

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(m => m.Id)
        <div class="form-group">
            <label for="Name">Name</label>
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Name)
        </div>
        <input type="submit" value="Submit" class="btn btn-secondary" />
    }
</div>

BookStore.WEB/Views/Author/ShowAuthors.cshtml
@model IEnumerable<BookStore.WEB.ViewModels.AuthorViewModel>
@Html.ActionLink("Добавить автора", "Create", null, new { @class = "btn btn-primary mb-2" })
<table class="table table-hover">
    <tbody>
    @foreach (var author in Model)
    {
        <tr>
            <td>@author.Name</td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Author", new { id = author.Id },
                    new {@class= "viewDialog", data_dialog_title = "Редактирование модели" })
            </td>
            <td>
                @Ajax.ActionLink("Delete", "Delete", "Author",
                    new { id =author.Id},new AjaxOptions { HttpMethod="POST",UpdateTargetId = "updateAdminPanel",Confirm = "Are you sure?"
                    })
            </td>
        </tr>
    }
    </tbody>
</table>
<script src="@Url.Content("~/Scripts/developerScripts/EditDialogScript.js")"></script>