BookStore.WEB/Controllers/Admin/GenreController.cs
using BookStore.BLL.Interfaces;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using BookStore.BLL.DTO;
using BookStore.WEB.Models;

namespace BookStore.WEB.Controllers.Admin
{
    public class GenreController : Controller
    {
        // GET: Genre
        private IBookService _bookService;
        private IAuthorService _authorService;
        private IGenreService _categoryService;

        public GenreController(IBookService bookService, IAuthorService authorService, IGenreService categoryService)
        {
            _categoryService = categoryService;
            _authorService = authorService;
            _bookService = bookService;
        }

        public ActionResult GetAllGenres()
        {
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<GenreDTO, CategoryViewModel>()).CreateMapper();
            var genres =
                mapper.Map<IEnumerable<GenreDTO>, IEnumerable<CategoryViewModel>>(_categoryService.GetCategories());
              return PartialView("ShowGenres", genres);
        }
        public ActionResult Delete(int id)
        {
            _categoryService.DeleteGenre(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<GenreDTO, CategoryViewModel>()).CreateMapper();
            var genres =
                mapper.Map<IEnumerable<GenreDTO>, IEnumerable<CategoryViewModel>>(_categoryService.GetCategories());
            return PartialView("ShowGenres", genres);
        }
        public ActionResult Edit(int id)
        {
            var genreDTO = _categoryService.GetGenre(id);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<GenreDTO, CategoryViewModel>()).CreateMapper();
            var viewModel = mapper.Map<GenreDTO, CategoryViewModel>(genreDTO);
            return PartialView(viewModel);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(CategoryViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CategoryViewModel, GenreDTO>())
                    .CreateMapper();
                var genre = mapper.Map<CategoryViewModel, GenreDTO>(viewModel);
                _categoryService.CreateGenre(genre);
                return RedirectToAction("Main", "Book");
            }

            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CategoryViewModel, GenreDTO>()).CreateMapper();
                var genre = mapper.Map<CategoryViewModel, GenreDTO>(viewModel);
                _categoryService.Update(genre);
                var mapperGenres = new MapperConfiguration(cfg => cfg.CreateMap<GenreDTO, CategoryViewModel>()).CreateMapper();
                var genres =
                    mapperGenres.Map<IEnumerable<GenreDTO>, IEnumerable<CategoryViewModel>>(_categoryService.GetCategories());
                return PartialView("ShowGenres", genres);

            }

            return PartialView("Edit", viewModel);
        }
    }
}

BookStore.WEB/Views/Genre/Create.cshtml
@model BookStore.WEB.Models.CategoryViewModel
@{
    ViewBag.Title = "Добавление книги";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Add Genre</h4>
@using (Html.BeginForm("Create","Genre"))
{
    @Html.AntiForgeryToken()
<div class="form-group">
    <label>Name</label>
    @Html.EditorFor(m => m.CategoryName, null, new { htmlAttributes = new { @class = "form-control col-sm-4", placeholder = "Например: Классика" } })
    @Html.ValidationMessageFor(m => m.CategoryName)
</div>
    <input type="submit" value="Submit" class="btn btn-primary"/>
}

BookStore.WEB/Views/Genre/ShowGenres.cshtml
@model IEnumerable<BookStore.WEB.Models.CategoryViewModel>
@Html.ActionLink("Add Genre", "Create", null, new { @class = "btn btn-primary mb-2" })
<table class="table table-hover">
    <tbody>
        @foreach (var category in Model)
        {
            <tr>
                <td>@category.CategoryName</td>
                <td>
                    @Html.ActionLink("Change", "Edit", "Genre", new { id = category.Id },
                        new {@class= "viewDialog", data_dialog_title = "Редактирование жанра" })
                </td>
                <td>
                    @Ajax.ActionLink("Delete", "Delete", "Genre",
                        new { id =category.Id},new AjaxOptions { HttpMethod="POST",UpdateTargetId = "updateAdminPanel",Confirm = "Вы действительно хотите удалить этот объект?"
                        })
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="@Url.Content("~/Scripts/developerScripts/EditDialogScript.js")"></script>